name: Robinhood Sell Puts Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1-4'  # Mon-Thu at 11:30 AM ET

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests robin_stocks yfinance PyYAML

      - name: Run Robinhood Sell Puts Scanner
        env:
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python robinhood_sell_puts.py
