name: Robinhood Sell Puts Scanner V2

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1'  # Every Monday 11:30 AM ET

jobs:
  run-scanner-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robin_stocks pandas matplotlib numpy scipy requests

      - name: Run V2 script
        env:
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python robinhood_sell_puts_chart_v2.py