name: Robinhood Sell Puts Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1'

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip wheel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip/wheels
          key: ${{ runner.os }}-pip-wheels-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-wheels-

      - name: Cache site-packages
        uses: actions/cache@v3
        with:
          path: ~/.local/lib/python3.11/site-packages
          key: ${{ runner.os }}-python3.11-site-packages-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python3.11-site-packages-

      - name: Install dependencies (if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade --quiet --prefer-binary -r requirements.txt

      - name: Run Robinhood Sell Puts Scanner
        env:
          RH_USERNAME: ${{ secrets.RH_USERNAME }}
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python robinhood_sell_puts.py
